### ISSUE TITLE
java-server-sdk 5.0.0 with aws-v1

### ISSUE THREAD

**Issue by davebarda** [launchdarkly/java-server-sdk-dynamodb#10]
Hey, seems like java-server-sdk 5.0.0 is not compatible with aws-v1,
as it doesn't have a method that creates PersistentDataStoreBuilder,
will it be created?

Thanks

**Comment by eli-darkly** [comment]
I'm not clear on what the "it" refers to in your question, but it's true that version 3.0 of this package uses AWS SDK v2 and requires Java SDK 5.0, as the readme says. We did not port the older AWS SDK v1 implementation from version 1.0 of this package to the new SDK interfaces, because AWS SDK v2 was released two years ago and in general we assume there's less demand for integrations with obsolete tools. Can you say more about why this is an issue for you?

**Comment by eli-darkly** [comment]
If there is a reason why an AWS SDK v1 integration for java-server-sdk 5.0 is necessary, I think we would have to release it as a separate package, since otherwise I can't imagine how the versioning of this package would work (that is, it couldn't be a 1.x version since the SDK dependency would be a breaking change, but it couldn't be 4.x since it doesn't follow on from 3.x).

**Comment by davebarda** [comment]
What about overloading the existingClient method(to keep the compatibility) and create a parallel implementation?
Actually that's the reason we keep using v1:
https://github.com/aws/aws-sdk-java-v2/issues/473
We will consider if we want to have v1 alongside v2, but in general, I think that it's an important feature.

Thanks!

**Comment by eli-darkly** [comment]
> What about overloading the existingClient method(to keep the compatibility) and create a parallel implementation?

Do you mean within a _single_ version of `java-server-sdk-dynamodb`? I don't see how that could possibly work; the v1 AWS client and the v2 AWS client don't have the same API; there's no way to write the implementation of this library to transparently use either one, it has to be written against one or the other. I also don't see why it would even be desirable to do it that way instead of just releasing another package.

**Comment by davebarda** [comment]
I just think that releasing it on the same package may enable someone who uses it.
I didn't mean to write it transparently, just to support both implementations.
There is Redis, DynamoV1 DynamoV2.
It means that DynamoDB with SDK v1 will be a first-class solution, and not just a workaround for people works with it.

**Comment by eli-darkly** [comment]
I'm sorry if I'm failing to understand your comment, but this still does not make sense to me. How would putting two completely separate implementations into the same package "enable" anyone? It's no harder to type the name of one package than another, and that has nothing to do with whether it is a "first-class solution".

Another reason not to put them both in one package is that doing so will bring in the entire transitive dependency tree for two versions of the AWS SDK. It is bad behavior for a library to include massive dependencies that will never be used at all by most of its users.

Finally, it would mess with the versioning and release process. When there are two completely separate code bases in a single package, which not only don't but _can't_ share any code, there will inevitably be fixes and releases that are only for one or the other. That's not a helpful experience for someone who's only using one of them and doesn't care at all about the other one.

All of the above are basically the same reasons that we do not make one big "all the database integrations" package that includes Redis, Consul, DynamoDB, etc. That, plus there's just no reason to do so in the first place.

**Comment by eli-darkly** [comment]
To be clear, I'm not against the idea of publishing a DynamoDB integration with AWS v1 that works with Java SDK 5.0. I'm just saying why, if and when we do that, it will likely be a separate package for all of the reasons I just mentioned. There is nothing unusual or non-"first-class" about that. It's the same situation as if we were to offer two different Redis integrations that use two different third-party Redis clients— they simply don't work the same way and aren't implemented the same way and it's not hard for people to decide which one they want to use.

**Comment by eli-darkly** [comment]
In any case, I've added this to our internal list of feature requests. I'll close this issue for now, but we'll reopen and comment on it if there are any developments, so following this issue is the best way to stay informed.
